[package]
name = "nexa_secp256k1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
sha2 = "0.10.7"
hex = "0.4.3"

[build-dependencies]
bindgen = "0.68"
cc = "1.0"

